// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "providerdapp-20181105055057--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d1kgzhpgc5hfa8.cloudfront.net"
};


export default awsmobile;
